{
  description = "Combine keys from multiple SSH agents into a single agent socket";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/4590696c8693fea477850fe379a01544293ca4e2";
    nixpkgs-master.url = "github:NixOS/nixpkgs/ae921939fcbd44874664477bd1d22543c10a8306";
    utils.url = "https://flakehub.com/f/numtide/flake-utils/0.1.102";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # batman test orchestrator + bats helper libs (bats-support,
    # bats-assert, bats-assert-additions, bats-island). Brings its own
    # amarbel-llc/nixpkgs fork on purpose: do NOT make it follow this
    # flake's upstream nixpkgs, or the fork's auto-applied overlay
    # (fence, buildZxScriptFromFile, …) goes missing.
    bats.url = "github:amarbel-llc/bats";
    # tap-dancer (TAP wrapper used by `just test-rust`). Same rationale —
    # leave its nixpkgs on the fork.
    tap.url = "github:amarbel-llc/tap";
    # treefmt-nix drives `nix fmt` and the read-only `checks.formatting`
    # gate (see `just lint-fmt` / `just codemod-fmt-treefmt`).
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      nixpkgs-master,
      utils,
      rust-overlay,
      bats,
      tap,
      treefmt-nix,
    }:
    # System-agnostic outputs (Home Manager module) merged with the per-system
    # outputs produced by eachDefaultSystem below.
    {
      homeManagerModules = rec {
        ssh-agent-mux = import ./nix/home-manager.nix self;
        default = ssh-agent-mux;
      };
    }
    // utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
        pkgs-master = import nixpkgs-master {
          inherit system;
          overlays = [ rust-overlay.overlays.default ];
        };
        rustToolchain = pkgs-master.rust-bin.stable.latest.default.override {
          extensions = [
            "rust-src"
            "rustfmt"
          ];
        };

        # Single source of truth for the version (eng-versioning(7)).
        # `just bump-version` keeps version.env and Cargo.toml in lock-step.
        version = builtins.head (
          builtins.match ".*SSH_AGENT_MUX_VERSION=([^\n]+).*" (builtins.readFile ./version.env)
        );

        # Formatting: rustfmt (pinned to the rust-overlay toolchain so it
        # honours edition 2024), nixfmt, shfmt, taplo, mdformat. Drives both
        # `nix fmt` (the `formatter` output) and the read-only `checks.formatting`.
        treefmtEval = treefmt-nix.lib.evalModule pkgs {
          projectRootFile = "flake.nix";
          programs.rustfmt = {
            enable = true;
            package = rustToolchain;
            edition = "2024";
          };
          programs.nixfmt.enable = true;
          programs.shfmt.enable = true;
          programs.taplo.enable = true;
          programs.mdformat.enable = true;
          # CHANGELOG.md is generated by git-cliff; leave its layout alone.
          settings.global.excludes = [ "CHANGELOG.md" ];
        };
      in
      {
        formatter = treefmtEval.config.build.wrapper;
        checks.formatting = treefmtEval.config.build.check self;

        packages.default = pkgs.rustPlatform.buildRustPackage {
          pname = "ssh-agent-mux";
          inherit version;

          src = ./.;

          cargoLock = {
            lockFile = ./Cargo.lock;
            outputHashes = {
              "ssh-agent-lib-0.6.0" = "sha256-wRVRMHvON7yzsswn8k069rbqt2+364Pda+jOcYlB5Pw=";
            };
          };

          nativeCheckInputs = [ pkgs.openssh ];

          # Skip integration tests in sandbox due to macOS SDK restrictions.
          # Tests work fine in nix develop, but fail in the stricter nix build sandbox
          # on macOS due to environment and filesystem restrictions.
          doCheck = !pkgs.stdenv.hostPlatform.isDarwin;

          postInstall = ''
            mkdir -p $out/share/ssh-agent-mux
            cat > $out/share/ssh-agent-mux/net.ross-williams.ssh-agent-mux.plist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>Label</key>
              <string>net.ross-williams.ssh-agent-mux</string>
              <key>ProgramArguments</key>
              <array>
                <string>$out/bin/ssh-agent-mux</string>
              </array>
              <key>KeepAlive</key>
              <true/>
              <key>RunAtLoad</key>
              <true/>
            </dict>
            </plist>
            EOF
            cat > $out/share/ssh-agent-mux/ssh-agent-mux.service <<EOF
            [Unit]
            Description=SSH Agent Multiplexer

            [Service]
            ExecStart=$out/bin/ssh-agent-mux
            Restart=on-failure

            [Install]
            WantedBy=default.target
            EOF
          '';

          meta = with pkgs.lib; {
            description = "Combine keys from multiple SSH agents into a single agent socket";
            homepage = "https://github.com/friedenberg/ssh-agent-mux";
            license = with licenses; [
              asl20
              bsd3
            ];
            maintainers = [ ];
          };
        };

        devShells.default = pkgs-master.mkShell {
          packages = [
            rustToolchain
            pkgs-master.cargo-deny
            pkgs-master.cargo-edit
            pkgs-master.cargo-watch
            pkgs-master.rust-analyzer
            pkgs.openssl
            pkgs.pkg-config
            pkgs.just
            # release trio (`just release`/`tag`): gum for log UI, git-cliff
            # for the changelog, gh to publish the GitHub release.
            pkgs.gum
            pkgs.git-cliff
            pkgs.gh
            bats.packages.${system}.batman
            # The `bats` binary itself --- the test-bats recipe invokes `bats`
            # directly, and the batman package alone does not put it on PATH.
            bats.packages.${system}.bats
            tap.packages.${system}.tap-dancer
          ];
        };
      }
    );
}
