{
  description = "Combine keys from multiple SSH agents into a single agent socket";

  inputs = {
    # Pinned to the nixos-26.05 release branch to stay aligned with the eng
    # workspace's nixpkgs (amarbel-llc/eng flake.nix). 26.05 carries the
    # `lib/services` framework that home-manager's module system now needs.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    nixpkgs-master.url = "github:NixOS/nixpkgs/ae921939fcbd44874664477bd1d22543c10a8306";
    utils.url = "https://flakehub.com/f/numtide/flake-utils/0.1.102";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # batman test orchestrator + bats helper libs (bats-support,
    # bats-assert, bats-assert-additions, bats-island). Brings its own
    # amarbel-llc/nixpkgs fork on purpose: do NOT make it follow this
    # flake's upstream nixpkgs, or the fork's auto-applied overlay
    # (fence, buildZxScriptFromFile, …) goes missing.
    bats.url = "github:amarbel-llc/bats";
    # tap-dancer (TAP wrapper used by `just test-rust`). Same rationale —
    # leave its nixpkgs on the fork.
    tap.url = "github:amarbel-llc/tap";
    # conformist fmt+lint pilot (ssh-agent-mux#16): `--commit` fix commits,
    # `--staged` lint-staged mode, `--trailer` (conformist#24/#25/#26).
    # Pinned to the rev that shipped --staged. Same rationale as bats/tap:
    # its igloo input is the load-bearing amarbel-llc nixpkgs fork (the Go
    # builders only exist there) — take its inputs as-is, no follows.
    conformist.url = "github:amarbel-llc/conformist/4edeb28944a7fd939d2ddd2b876c2cb2dc5ad075";
    # treefmt-nix drives `nix fmt` and the read-only `checks.formatting`
    # gate (see `just lint-fmt` / `just codemod-fmt-treefmt`).
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # home-manager supplies the module system behind the faithful
    # `checks.home-manager-module` eval check (ssh-agent-mux#13). Follows this
    # flake's nixpkgs so the module evaluates against the same package set the
    # binary is built from.
    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      nixpkgs-master,
      utils,
      rust-overlay,
      bats,
      tap,
      conformist,
      treefmt-nix,
      home-manager,
    }:
    # System-agnostic outputs (Home Manager module) merged with the per-system
    # outputs produced by eachDefaultSystem below.
    {
      homeManagerModules = rec {
        ssh-agent-mux = import ./nix/home-manager.nix self;
        default = ssh-agent-mux;
      };
    }
    // utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
        pkgs-master = import nixpkgs-master {
          inherit system;
          overlays = [ rust-overlay.overlays.default ];
        };
        rustToolchain = pkgs-master.rust-bin.stable.latest.default.override {
          extensions = [
            "rust-src"
            "rustfmt"
          ];
        };

        # Single source of truth for the version (eng-versioning(7)).
        # `just bump-version` keeps version.env and Cargo.toml in lock-step.
        version = builtins.head (
          builtins.match ".*SSH_AGENT_MUX_VERSION=([^\n]+).*" (builtins.readFile ./version.env)
        );

        # Formatting: rustfmt (pinned to the rust-overlay toolchain so it
        # honours edition 2024), nixfmt, shfmt, taplo, mdformat. Drives both
        # `nix fmt` (the `formatter` output) and the read-only `checks.formatting`.
        treefmtEval = treefmt-nix.lib.evalModule pkgs {
          projectRootFile = "flake.nix";
          programs.rustfmt = {
            enable = true;
            package = rustToolchain;
            edition = "2024";
          };
          programs.nixfmt.enable = true;
          programs.shfmt.enable = true;
          programs.taplo.enable = true;
          programs.mdformat.enable = true;
          # CHANGELOG.md is generated by git-cliff; leave its layout alone.
          settings.global.excludes = [ "CHANGELOG.md" ];
        };

        # Bats integration suite as a nix-sandboxed lane (bats-lane(7)).
        # Authoritative gate for `just test-bats`: the host fence-wrapped
        # bats is unreliable on some machines (fence bridge init timeout),
        # so the suite runs hermetically against the nix-built binary
        # instead. Exposed as both packages.bats-default (so plain
        # `nix build .#bats-default` works) and checks.bats-default
        # (`nix flake check`).
        batsDefaultLane = bats.lib.${system}.batsLane {
          base = self.packages.${system}.default;
          binaryName = "ssh-agent-mux";
          binaryEnvVarName = "SSH_AGENT_MUX_BIN";
          batsSrc = ./zz-tests_bats;
          batsLibPath = [ bats.packages.${system}.bats-libs.batsLibPath ];
          # bats-island's setup_test_home shells out to git, which is not
          # on the nix builder's default PATH (bats-lane(7) NIX-BUILDER
          # CAVEATS).
          nativeBuildInputs = [ pkgs.git ];
          # Host runs budget 5s per test (zz-tests_bats/justfile); sandbox
          # builds are slower, so budget 30s. The inner `timeout 2s`
          # wrapper in common.bash is deliberately unchanged.
          extraEnv.BATS_TEST_TIMEOUT = "30";
        };
      in
      {
        formatter = treefmtEval.config.build.wrapper;
        checks.formatting = treefmtEval.config.build.check self;
        checks.bats-default = batsDefaultLane;

        # Faithful eval of the Home Manager module (ssh-agent-mux#13): builds a
        # sample homeManagerConfiguration that enables services.ssh-agent-mux,
        # forces its activation package (firing the assertions and rendering the
        # systemd unit + config), then validates the rendered TOML against the
        # binary. Exercises the module itself --- option declarations, mkMerge
        # wiring, assertions, unit attrs --- not just the settings mapping.
        checks.home-manager-module =
          let
            hmConfig = home-manager.lib.homeManagerConfiguration {
              inherit pkgs;
              modules = [
                self.homeManagerModules.default
                {
                  home.username = "tester";
                  home.homeDirectory = "/home/tester";
                  home.stateVersion = "24.11";
                  services.ssh-agent-mux = {
                    enable = true;
                    addNewKeysTo = "1password";
                    agents = [
                      {
                        name = "1password";
                        socketPath = "~/.1password/agent.sock";
                      }
                      {
                        name = "yubikey";
                        socketPath = "~/.ssh/yubikey-agent.sock";
                        enabled = false;
                      }
                    ];
                    # Exercise the freeform escape hatch and its precedence.
                    settings.log-level = "debug";
                  };
                }
              ];
            };
            renderedConfig = hmConfig.config.xdg.configFile."ssh-agent-mux/ssh-agent-mux.toml".source;
          in
          pkgs.runCommand "ssh-agent-mux-home-manager-module-check"
            {
              # Build the activation package so the module's assertions and unit
              # files are evaluated and realized, not just the config TOML.
              inherit (hmConfig) activationPackage;
            }
            ''
              export HOME="$TMPDIR"
              ${self.packages.${system}.default}/bin/ssh-agent-mux \
                --config ${renderedConfig} config validate
              touch "$out"
            '';

        packages.bats-default = batsDefaultLane;

        packages.default = pkgs.rustPlatform.buildRustPackage {
          pname = "ssh-agent-mux";
          inherit version;

          src = ./.;

          cargoLock = {
            lockFile = ./Cargo.lock;
            outputHashes = {
              "ssh-agent-lib-0.6.0" = "sha256-wRVRMHvON7yzsswn8k069rbqt2+364Pda+jOcYlB5Pw=";
              "tap-dancer-0.1.13" = "sha256-bc/QI5TCZZwK0RLzSoUMZjqUk0YOIeQhOFANFF0PgF0=";
            };
          };

          nativeCheckInputs = [ pkgs.openssh ];

          # Skip integration tests in sandbox due to macOS SDK restrictions.
          # Tests work fine in nix develop, but fail in the stricter nix build sandbox
          # on macOS due to environment and filesystem restrictions.
          doCheck = !pkgs.stdenv.hostPlatform.isDarwin;

          postInstall = ''
            mkdir -p $out/share/ssh-agent-mux
            cat > $out/share/ssh-agent-mux/net.ross-williams.ssh-agent-mux.plist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>Label</key>
              <string>net.ross-williams.ssh-agent-mux</string>
              <key>ProgramArguments</key>
              <array>
                <string>$out/bin/ssh-agent-mux</string>
              </array>
              <key>KeepAlive</key>
              <true/>
              <key>RunAtLoad</key>
              <true/>
            </dict>
            </plist>
            EOF
            cat > $out/share/ssh-agent-mux/ssh-agent-mux.service <<EOF
            [Unit]
            Description=SSH Agent Multiplexer

            [Service]
            ExecStart=$out/bin/ssh-agent-mux
            Restart=on-failure

            [Install]
            WantedBy=default.target
            EOF
          '';

          meta = with pkgs.lib; {
            description = "Combine keys from multiple SSH agents into a single agent socket";
            homepage = "https://github.com/friedenberg/ssh-agent-mux";
            license = with licenses; [
              asl20
              bsd3
            ];
            maintainers = [ ];
          };
        };

        devShells.default = pkgs-master.mkShell {
          packages = [
            rustToolchain
            pkgs-master.cargo-deny
            pkgs-master.cargo-edit
            pkgs-master.cargo-watch
            pkgs-master.rust-analyzer
            pkgs.openssl
            pkgs.pkg-config
            pkgs.just
            # release trio (`just release`/`tag`): gum for log UI, git-cliff
            # for the changelog, gh to publish the GitHub release.
            pkgs.gum
            pkgs.git-cliff
            pkgs.gh
            bats.packages.${system}.batman
            # The `bats` binary itself --- the test-bats recipe invokes `bats`
            # directly, and the batman package alone does not put it on PATH.
            bats.packages.${system}.bats
            tap.packages.${system}.tap-dancer
            # conformist pilot (ssh-agent-mux#16). conformist-bga is the
            # plain input-addressed build; the default package is godyn
            # (ca-derivations), which this host's nix doesn't enable.
            conformist.packages.${system}.conformist-bga
            # conformist resolves formatter binaries from PATH
            # (conformist.toml uses bare command names). These are the
            # same nixpkgs packages the treefmt eval pins, so check/fix
            # stay byte-identical with the existing lint-fmt gate;
            # rustfmt comes from the toolchain above.
            pkgs.nixfmt
            pkgs.shfmt
            pkgs.taplo
            pkgs.mdformat
          ];

          # bats-lane(7)/bats-testing(7) manpages for agents exploring the
          # test harness. The batman-manpages package ships share/man only
          # (no bin/), so man(1)'s PATH-based inference never finds it ---
          # export it on MANPATH explicitly. The trailing colon keeps the
          # system man path reachable.
          shellHook = ''
            export MANPATH="${bats.packages.${system}.batman-manpages}/share/man''${MANPATH:+:$MANPATH}:"
          '';
        };
      }
    );
}
